services:
  mongo:
    image: mongo:8.0
    container_name: stellux-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db # 挂载数据目录
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    env_file:
      - ./config/stellux.production.yaml
    command: --auth --bind_ip_all
    restart: always

  server:
    image: codepzj/stellux-server:latest
    container_name: stellux-server
    depends_on:
      - mongo
    ports:
      - 9001:9001
    restart: always
    volumes:
      - ./config:/app/config # 挂载配置文件
      - ./static:/app/static # 挂载静态文件
      - ./log:/app/log # 挂载日志文件